# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - inventoryoutlier

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt -t .python_packages/lib/site-packages
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Verify package contents
        run: |
          ls -la
          ls -la .python_packages/lib/site-packages

      - name: Zip artifact for deployment
        run: |
          mkdir deployment
          cp -r .python_packages deployment/
          cp function_app.py deployment/
          cp host.json deployment/
          cp requirements.txt deployment/
          cd deployment
          zip -r ../release.zip .

      - name: Verify ZIP contents
        run: |
          unzip -l release.zip | grep numpy
          unzip -l release.zip | grep ".python_packages"
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D5882E1B63F472E82ACA6E3AA996DA9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E4EE63D4583448CCA19A9D365A7D4FD3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ECF1B4EC967D4D4EA4A3831A0A5261F0 }}
          
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'inventoryoutlier'
          slot-name: 'Production'
          package: release.zip
